services:
  streamlit:
    build: ./streamlit
    volumes:
      - ./data:/data:ro
    ports:
      - "8501:8501"
    depends_on:
      - qdrant

  fastapi:
    build: ./fastapi
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  wal_processor:
    build: ./background
    volumes:
      - ./data:/data
    depends_on:
      - fastapi  # ✅ optionally wait for FastAPI to start writing

volumes:
  qdrant_data: